export const GOOGLE_SIGNIN = {
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    LOGOUT: 'LOGOUT'
};

export const VOCAB_WORDS = {
    ADD: {
        IN_PROGRESS: 'ADD_WORD_IN_PROGRESS',
        SUCCESS: 'ADD_WORD_SUCCESS',
        ERROR: 'ADD_WORD_ERROR'
    },
    GET_BY_ID: {
        IN_PROGRESS: 'GET_WORD_BY_ID_IN_PROGRESS',
        SUCCESS: 'GET_WORD_BY_ID_SUCCESS',
        ERROR: 'GET_WORD_BY_ID_ERROR'
    }, 
    GET_BY_USERID: {
        IN_PROGRESS: 'GET_WORDS_BY_USERID_IN_PROGRESS',
        SUCCESS: 'GET_WORDS_BY_USERID_SUCCESS',
        ERROR: 'GET_WORDS_BY_USERID_ERROR'
    },
    UPDATE: {
        IN_PROGRESS: 'UPDATE_WORD_IN_PROGRESS',
        SUCCESS: 'UPDATE_WORD_SUCCESS',
        ERROR: 'UPDATE_WORD_ERROR'
    },
    DELETE: {
        IN_PROGRESS: 'DELETE_WORD_IN_PROGRESS',
        SUCCESS: 'DELETE_WORD_SUCCESS',
        ERROR: 'DELETE_WORD_ERROR'
    }
}
